### ISSUE TITLE
More distinguishable diff colors?

### ISSUE THREAD

**Issue by 3N4N** [axvr/photon.vim#1]
Hi,

Nice colorscheme. I wanted to have your view on diff colors.

I had previously my diff colors to [look like the this](https://imgur.com/PsxrjlO).
![image](https://user-images.githubusercontent.com/32037751/55271505-cf3f7700-52d7-11e9-9088-c622ad83af01.png)

But I couldn't see my cursor properly, so, I exchanged background colors with foreground colors [like this](https://imgur.com/VDwWcHn).
![image](https://user-images.githubusercontent.com/32037751/55271513-eaaa8200-52d7-11e9-9d24-11865bbd442b.png)

But now, it's hard to mark the diff blocks easily. I am currently trying to figure out if I can use `:h signs` to place `+` and `-` signs in diff mode to make it more obvious. But it's out of my league.

What is your take on this?

**Comment by axvr** [comment]
From my experience with building photon, I can say with confidence that diff colours are by far the most difficult highlight groups to get right (I'm still not 100% happy with the ones in photon - but they are good enough for the time being).

What makes it so difficult to configure them well is the fact that Vimdiff still syntax highlights the rest of the file, which prevents diff blocks standing out unless you do what you showed in your first screenshot.

As you said, it is certainly possible to add `+` and `-` signs to the sign column, but this approach isn't particularly practical as you may end up interfering with the fold markers Vim diff uses.

I would say your best bet is to try and use colours that you haven't used before in your colour scheme or change the background colour of the diff groups (`DiffAdd`, `DiffDelete`, `DiffChange` and `DiffText`), to either a slightly lighter or darker variant of your `Normal` background colour.

**Comment by 3N4N** [comment]
Hmm, but I turn off nearly every color for every highlight group. So, I'm gonna stay with what I have right now. Thanks.
