### ISSUE TITLE
Light theme possible?

### ISSUE THREAD

**Issue by craigmac** [axvr/photon.vim#2]
Thanks for photon, I really love it! I'm usually a light theme kind of guy though: is there an easy way to make a light theme version of this, similar to what Paramount did?

**Comment by axvr** [comment]
I definitely want to create a light variant of Photon.  I'm rather busy this month trying to finish off another project, so won't be able to work on it for a while, but I'll comment here once it's ready.

**Comment by axvr** [comment]
Hi @craigmac, I've pushed a branch called `antiphoton` containing the first version of the light theme variant.

```vim
colorscheme antiphoton
```

If you try it, let me know your thoughts and if you think anything could be improved.
![image](https://user-images.githubusercontent.com/26504626/102716069-52390a00-42d1-11eb-9803-5f933edffbdc.png)

**Comment by craigmac** [comment]
Working well for me so far, love the colour choices and the popup menu. Thanks!

**Comment by axvr** [comment]
Excellent.  I made some minor adjustments and the new theme has now been added to the `master` branch.
