### ISSUE TITLE
unspecified color seen in `:Rg` results using fzf.vim

### ISSUE THREAD

**Issue by dakahn** [axvr/photon.vim#5]
Hello! Really like the theme but wanted to draw your attention to line number references in ripgreg results using fzf.vim(in green)
![image](https://user-images.githubusercontent.com/40970507/126706705-7e842a7a-5ef8-4452-bc8a-000acc562ca1.png)

Potentially helpful -- here are the various tokens used by fzf for applying a colorscheme's style to the plugin dialog seen when you `:Rg`
![image](https://user-images.githubusercontent.com/40970507/126707077-449fa052-4c6c-45f4-808b-3b103bb779ff.png)
Im thinking that if one of these isn't specified by the plugin it would revert to defaults 🤷🏽‍♂️ 
Thanks again for making a really cool colorscheme

**Comment by axvr** [comment]
@dakahn, if you run the command `:highlight` you should see a list like the one below.  Can you see that (exact) green colour in the list?  (Remember to scroll with the `f` and `b` keys.)

![image](https://user-images.githubusercontent.com/26504626/126866361-594acb59-3c06-4161-8ba2-d8272448984c.png)

**Comment by axvr** [comment]
If this problem is what I think it is, it should now be fixed, so I'm closing this issue.  If anyone still encounters this problem please leave a comment.
